# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:

  build:
    working_directory: ~/repo

    machine:
      image: ubuntu-2004:202201-02
      docker_layer_caching: true
      resource_class: medium

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install git
            pip install --upgrade pip
            pip install awscli
            pip install wheel
      - run:
          name: build docker image
          no_output_timeout: 30m

          command: |
            aws ecr get-login --no-include-email --region us-east-1
            cd ~/repo
            docker build . -t mlflow
      - deploy:
          name: push docker image

          command: |
            echo 'Pushing image to OPS ECR'
            aws ecr get-login --no-include-email --region us-east-1 | bash
            docker tag mlflow:latest "${ECR_ENDPOINT}/mlflow:${CIRCLE_SHA1}"
            docker push "${ECR_ENDPOINT}/mlflow:${CIRCLE_SHA1}"
workflows:
  version: 2
  test_build:
    jobs:
      - build: {}
