version: 2.1
jobs:

  build:
    docker:
      - image: $ECR_ENDPOINT/image-builder:master

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: build docker image
          no_output_timeout: 30m

          command: |
            build-and-push --image mlflow --file Dockerfile --build-dir .
            
workflows:
  version: 2
  test_build:
    jobs:
      - build:
          context:
            - ecr
